version: 2
updates:dependabot.yml
  - package-ecosystem: github-actions
    directory: "/"
    schedule: kiểm tra bảo mật& vá lổ hổng bảo mật
      interval: daily
      time: "10:00"
      timezone: Europe/VietNam
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
    rebase-strategy: doanh nghiệp
